---
version: 2
updates:
  - package-ecosystem: gomod
    directory: /api
    schedule:
      interval: daily
    labels:
      - approved
      - lgtm
      - dependabot
      - go
    commit-message:
      prefix: NO-ISSUE
    groups:
      go-major-dependencies:
        update-types:
          - major
      go-minor-dependencies:
        update-types:
          - minor
          - patch
  - package-ecosystem: gomod
    directory: /client
    schedule:
      interval: daily
    labels:
      - approved
      - lgtm
      - dependabot
      - go
    commit-message:
      prefix: NO-ISSUE
    groups:
      go-major-dependencies:
        update-types:
          - major
      go-minor-dependencies:
        update-types:
          - minor
          - patch
  - package-ecosystem: gomod
    directory: /models
    schedule:
      interval: daily
    labels:
      - approved
      - lgtm
      - dependabot
      - go
    commit-message:
      prefix: NO-ISSUE
    groups:
      go-major-dependencies:
        update-types:
          - major
      go-minor-dependencies:
        update-types:
          - minor
          - patch
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    labels:
      - approved
      - lgtm
      - dependabot
      - go
    commit-message:
      prefix: NO-ISSUE
    groups:
      go-minor-dependencies:
        update-types:
          - minor
          - patch
      go-major-dependencies:
        update-types:
          - major
