---
version: 2
updates:
  - package-ecosystem: gomod
    versioning-strategy: increase
    directory: /api
    schedule:
      interval: daily
    labels:
      - approved
      - lgtm
      - dependabot
      - go
    commit-message:
      prefix: NO-ISSUE
    groups:
      go-minor-api-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

      go-major-api-dependencies:
        patterns:
          - "*"
        update-types:
          - major

  - package-ecosystem: gomod
    versioning-strategy: increase
    directory: /client
    schedule:
      interval: daily
    labels:
      - approved
      - lgtm
      - dependabot
      - go
    commit-message:
      prefix: NO-ISSUE
    groups:
      go-minor-client-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
          
      go-major-client-dependencies:
        patterns:
          - "*"
        update-types:
          - major
          
  - package-ecosystem: gomod
    versioning-strategy: increase
    directory: /models
    schedule:
      interval: daily
    labels:
      - approved
      - lgtm
      - dependabot
      - go
    commit-message:
      prefix: NO-ISSUE
    groups:
      go-minor-models-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
          
      go-major-models-dependencies:
        patterns:
          - "*"

  - package-ecosystem: gomod
    versioning-strategy: increase
    directory: /
    schedule:
      interval: daily
    labels:
      - approved
      - lgtm
      - dependabot
      - go
    commit-message:
      prefix: NO-ISSUE
    groups:
      go-minor-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
          
      go-major-dependencies:
        patterns:
          - "*"
        update-types:
          - major
