---
version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - "/api"
      - "/models"
      - "/client"
    schedule:
      interval: daily
    labels:
      - approved
      - lgtm
      - dependabot
      - go
    commit-message:
      prefix: NO-ISSUE
    ignore:
      - dependency-name: "*k8s.io/*"
      - dependency-name: "github.com/openshift/*"
    groups:
      go-submodule-dependencies:
        update-types:
          - minor
          - patch
      go-submodule-major-dependencies:
        update-types:
          - major

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    labels:
      - approved
      - lgtm
      - dependabot
      - go
    commit-message:
      prefix: NO-ISSUE
    ignore:
      - dependency-name: "*k8s.io/*"
      - dependency-name: "github.com/openshift/*"
    groups:
      go-dependencies:
        update-types:
          - minor
          - patch
      go-major-dependencies:
        update-types:
          - major
    
