# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/api"
    schedule:
      interval: "daily"
    labels:
      - "approved"
      - "lgtm"
      - "dependabot"
      - "go"
    commit-message:
      prefix: "NO-ISSUE"
    groups:
      go-api-dependencies:
        dependency-type: "production"
        patterns: 
          - "*"
  - package-ecosystem: "gomod"
    directory: "/client"
    schedule:
      interval: "daily"
    labels:
      - "approved"
      - "lgtm"
      - "dependabot"
      - "go"
    commit-message:
      prefix: "NO-ISSUE"
    groups:
      go-client-dependencies:
        dependency-type: "production"
        patterns: 
          - "*"
  - package-ecosystem: "gomod"
    directory: "/models"
    schedule:
      interval: "daily"
    labels:
      - "approved"
      - "lgtm"
      - "dependabot"
      - "go"
    commit-message:
      prefix: "NO-ISSUE"
    groups:
      go-models-dependencies:
        dependency-type: "production"
        patterns: 
          - "*"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "approved"
      - "lgtm"
      - "dependabot"
      - "go"
    commit-message:
      prefix: "NO-ISSUE"
    groups:
      go-dependencies:
        dependency-type: "production"
        patterns: 
          - "*"
