---
version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - "/api"
      - "/models"
      - "/client"
    schedule:
      interval: daily
    labels:
      - approved
      - lgtm
      - dependabot
      - go
    commit-message:
      prefix: NO-ISSUE
    groups:
      go-submodule-dependencies:
        exclude-patterns:
        - "github.com/openshift/*"


  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    labels:
      - approved
      - lgtm
      - dependabot
      - go
    commit-message:
      prefix: NO-ISSUE
    # ignore:
    #   - dependency-name: k8s.io/*
    groups:
      go-dependencies:
        exclude-patterns:
        - "github.com/openshift/*"
    
